-- AlterTable
ALTER TABLE "Task" ADD COLUMN "actionType" TEXT;
ALTER TABLE "Task" ADD COLUMN "actualDays" INTEGER DEFAULT 0;
ALTER TABLE "Task" ADD COLUMN "actualEndDate" DATETIME;
ALTER TABLE "Task" ADD COLUMN "completedBy" TEXT;
ALTER TABLE "Task" ADD COLUMN "evidence" TEXT;
ALTER TABLE "Task" ADD COLUMN "ragRating" TEXT DEFAULT 'GREEN';
ALTER TABLE "Task" ADD COLUMN "variance" TEXT;
