[build]
  command = "npx prisma generate && npm run build && mkdir -p .next/standalone/prisma && cp prisma/schema.prisma .next/standalone/prisma/ && cp prisma/dev.db .next/standalone/prisma/"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
